# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "UserMessage" do
    optional :id, :int32, 1
    optional :name, :string, 2
    optional :email, :string, 3
    optional :mobile, :string, 4
  end
end

UserMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("UserMessage").msgclass
